// Generated by CoffeeScript 1.3.3
(function() {

  (typeof exports !== "undefined" && exports !== null ? exports : this).samples = [
    {
      "item": "Shopping",
      "archived": false,
      "list": "Shopping-List",
      "idx": "001"
    }, {
      "item": "Groceries",
      "archived": false,
      "list": "Shopping-List",
      "idx": "001.001"
    }, {
      "item": "Milk",
      "archived": false,
      "list": "Shopping-List",
      "idx": "001.001.001"
    }, {
      "item": "Bread",
      "archived": false,
      "list": "Shopping-List",
      "idx": "001.001.002"
    }, {
      "item": "Household",
      "archived": false,
      "list": "Shopping-List",
      "idx": "001.002"
    }, {
      "item": "Soap",
      "archived": false,
      "list": "Shopping-List",
      "idx": "001.002.001"
    }
  ];

}).call(this);
