// Generated by CoffeeScript 1.3.3
(function() {
  var Items, blankItem, canonicalListName, itemMapping, listModel, newListModel, reset_data, viewModel, vm;

  Items = new Meteor.Collection('items');

  reset_data = function() {
    var sample, samples, _i, _len;
    Items.remove({
      list: (typeof vm.listName === "function" ? vm.listName() : void 0) || 'Sample'
    });
    samples = [
      {
        "isEditing": false,
        "item": "Current Sprint",
        "indent": 0,
        "archived": false,
        "list": "Sample",
        "sortOrder": 0,
        "_id": "e5da7063-bebb-41f0-b083-bd8d5a02b632"
      }, {
        "isEditing": false,
        "item": "Archive before delete",
        "indent": 1,
        "archived": true,
        "list": "Sample",
        "sortOrder": 8,
        "_id": "2159a75a-705f-48ae-9605-adb472a6177b"
      }, {
        "isEditing": false,
        "item": "Ability to unarchive",
        "indent": 1,
        "archived": true,
        "list": "Sample",
        "sortOrder": 16,
        "_id": "d90417b7-6fee-466b-8a64-c593b5199483"
      }, {
        "isEditing": false,
        "item": "Bigger, better action icons. Change to buttons?",
        "indent": 1,
        "archived": true,
        "list": "Sample",
        "sortOrder": 24,
        "_id": "1e9a1e68-45f9-41cb-b158-6219852cf84f"
      }, {
        "isEditing": false,
        "item": "Ability to rearrange items",
        "indent": 1,
        "archived": true,
        "list": "Sample",
        "sortOrder": 32,
        "_id": "38065f1d-3c8a-4321-8007-7e3408095cd8"
      }, {
        "isEditing": false,
        "item": "Should not be able to outdent past 0",
        "indent": 1,
        "archived": true,
        "list": "Sample",
        "sortOrder": 40,
        "_id": "3b336c23-5532-4d46-a1cb-98eb3a6a37f5"
      }, {
        "isEditing": false,
        "item": "Ability to create a new uniquely named list",
        "indent": 1,
        "archived": true,
        "list": "Sample",
        "sortOrder": 44,
        "_id": "d0c4ff23-2560-452b-940b-d220e128314a"
      }, {
        "isEditing": false,
        "item": "Shareable url for each list",
        "indent": 1,
        "archived": true,
        "list": "Sample",
        "sortOrder": 46,
        "_id": "d3b8cc8e-bcae-4b13-858f-bb03463002ef"
      }, {
        "_id": "f741e7c6-71fb-4b01-8ff1-95f78ed81f38",
        "isEditing": false,
        "item": "Ability to clear archived items",
        "indent": 1,
        "archived": true,
        "sortOrder": 47,
        "list": "Sample"
      }, {
        "_id": "74aba5f8-6d52-4cb4-931f-4cd4e40c2293",
        "isEditing": false,
        "item": "Ability to archive all items",
        "indent": 1,
        "archived": true,
        "sortOrder": 47.5,
        "list": "Sample"
      }, {
        "_id": "dde8a646-084c-4073-8cb4-4d415724b904",
        "isEditing": false,
        "item": "Should not be able to indent more than one level below parent",
        "indent": 1,
        "archived": false,
        "list": "Sample",
        "sortOrder": 47.75
      }, {
        "isEditing": false,
        "item": "Children should move with parent",
        "indent": 1,
        "archived": false,
        "list": "Sample",
        "sortOrder": 48,
        "_id": "2a96fa17-36ca-4536-88ce-94e763d64933"
      }, {
        "isEditing": false,
        "item": "Children should archive/delete with parent",
        "indent": 1,
        "archived": false,
        "list": "Sample",
        "sortOrder": 64,
        "_id": "fef1e673-5369-45c0-bdf7-833134c3a337"
      }, {
        "isEditing": false,
        "item": "Children should indent/outdent with parent",
        "indent": 1,
        "archived": false,
        "list": "Sample",
        "sortOrder": 72,
        "_id": "d0d06cac-382a-48cb-83b0-65d7dd0bbd9e"
      }, {
        "_id": "3625d6c1-d406-4793-8886-b0294e455ff8",
        "isEditing": false,
        "item": "Ability to insert an item anywhere in the list",
        "indent": 1,
        "archived": false,
        "list": "Sample",
        "sortOrder": 92
      }, {
        "isEditing": false,
        "item": "Backlog",
        "indent": 0,
        "archived": false,
        "list": "Sample",
        "sortOrder": 104,
        "_id": "5ffcf743-8940-4321-8029-b6b1bbf2be31"
      }, {
        "isEditing": false,
        "item": "Ability to password protect a list",
        "indent": 1,
        "archived": false,
        "list": "Sample",
        "sortOrder": 112,
        "_id": "d0524a04-b728-4f6f-9e45-6443849e44d0"
      }, {
        "isEditing": false,
        "item": "Ability to add a checkbox column, parent indicates number of checked children",
        "indent": 1,
        "archived": false,
        "list": "Sample",
        "sortOrder": 120,
        "_id": "54d8b5c8-d337-40be-aea1-1c71bde1b570"
      }, {
        "isEditing": false,
        "item": "Ability to add a numeric column, parent shows sum of children",
        "indent": 1,
        "archived": false,
        "list": "Sample",
        "sortOrder": 128,
        "_id": "1195ca4b-04d7-4e4f-8aa3-ab46ae8f2f90"
      }, {
        "isEditing": false,
        "item": "Textarea instead of single line textbox. Should grow instead of scroll and allow line breaks",
        "indent": 1,
        "archived": false,
        "list": "Sample",
        "sortOrder": 136,
        "_id": "a12fc44f-077e-421d-82f7-c183038f98b8"
      }
    ];
    for (_i = 0, _len = samples.length; _i < _len; _i++) {
      sample = samples[_i];
      Items.insert({
        item: sample.item,
        indent: sample.indent,
        archived: sample.archived,
        list: (typeof vm.listName === "function" ? vm.listName() : void 0) || 'Sample',
        sortOrder: sample.sortOrder
      });
    }
  };

  if (Meteor.is_client) {
    itemMapping = {
      item: {
        create: function(options) {
          var observable, parent;
          parent = options.parent;
          observable = ko.observable(options.data);
          parent.isEditing = ko.observable(false);
          parent.modeTemplate = function() {
            if (parent.isEditing()) {
              return 'itemEditing';
            } else {
              return 'item';
            }
          };
          parent.setEditing = function() {
            return parent.isEditing(true);
          };
          parent.clearEditing = function() {
            return parent.isEditing(false);
          };
          parent.doIndent = function() {
            return parent.indent(parent.indent() + 1);
          };
          parent.doOutdent = function() {
            if (parent.indent() > 0) {
              return parent.indent(parent.indent() - 1);
            }
          };
          parent.save = function() {
            parent.isEditing(false);
            return Items.update(parent._id(), {
              $set: {
                item: parent.item(),
                indent: parent.indent(),
                archived: false
              }
            });
          };
          parent.remove = function() {
            if (parent.archived()) {
              return Items.remove(parent._id());
            } else {
              return Items.update(parent._id(), {
                $set: {
                  archived: true
                }
              });
            }
          };
          return observable;
        }
      }
    };
    blankItem = function() {
      var _this = this;
      this.item = ko.observable('');
      this.indent = ko.observable(0);
      this.save = function() {
        var items;
        items = vm.vm().items();
        Items.insert({
          item: _this.item(),
          indent: _this.indent(),
          archived: false,
          sortOrder: items.length ? items[items.length - 1].sortOrder() + 8 : 0,
          list: vm.listName()
        });
        return _this.item('');
      };
      this.doIndent = function() {
        return _this.indent(_this.indent() + 1);
      };
      this.doOutdent = function() {
        if (_this.indent() > 0) {
          return _this.indent(_this.indent() - 1);
        }
      };
    };
    newListModel = function(parent) {
      var _this = this;
      this.name = ko.observable('');
      this.save = function() {
        Session.set('listName', canonicalListName(_this.name()));
        window.location.href = 'http://' + window.location.host + '/#!' + canonicalListName(_this.name());
        window.location.reload();
      };
    };
    listModel = function(parent) {
      var checkIndentationKeyBindings, indentOn2LeadingSpaces, isMoving, itemToInsert, items, moveHere, moveItem, movingItemId, outdentOnBackspaceAndEmpty, saveOnEnter, _this;
      _this = this;
      items = ko.meteor.find(Items, {
        list: parent.listName()
      }, {
        sort: {
          sortOrder: 1
        }
      }, itemMapping);
      itemToInsert = new blankItem();
      isMoving = ko.observable(false);
      movingItemId = '';
      indentOn2LeadingSpaces = function(model, event) {
        if (event.which !== 32) {
          return;
        }
        if (model.item().substr(0, 2) !== '  ') {
          return;
        }
        model.item(model.item().substring(2));
        return model.doIndent();
      };
      outdentOnBackspaceAndEmpty = function(model, event) {
        if (event.which !== 8) {
          return;
        }
        if (model.item() !== '') {
          return;
        }
        return model.doOutdent();
      };
      checkIndentationKeyBindings = function(model, event) {
        indentOn2LeadingSpaces(model, event);
        return outdentOnBackspaceAndEmpty(model, event);
      };
      saveOnEnter = function(model, event) {
        if (event.which !== 13) {
          return true;
        }
        model.save();
        return false;
      };
      moveItem = function(data) {
        movingItemId = data._id();
        items.remove(data);
        return isMoving(true);
      };
      moveHere = function(data) {
        var newSortOrder, nextItem;
        nextItem = items()[items.indexOf(data) + 1];
        newSortOrder = data.sortOrder() + 10;
        try {
          newSortOrder = data.sortOrder() + (nextItem.sortOrder() - data.sortOrder()) / 2;
        } catch (_error) {}
        Items.update(movingItemId, {
          $set: {
            sortOrder: newSortOrder
          }
        });
        movingItemId = '';
        return isMoving(false);
      };
      return {
        items: items,
        itemToInsert: itemToInsert,
        checkIndentationKeyBindings: checkIndentationKeyBindings,
        saveOnEnter: saveOnEnter,
        moveItem: moveItem,
        isMoving: isMoving,
        moveHere: moveHere
      };
    };
    viewModel = function() {
      var _this = this;
      this.listName = ko.observable(canonicalListName(Session.get('listName')));
      this.showingJSON = ko.observable(false);
      this.json = ko.observable('');
      this.templateToUse = function() {
        if (_this.listName()) {
          return 'socialist';
        } else {
          return 'newList';
        }
      };
      this.vm = ko.observable(this.listName() === '' ? new newListModel(this) : new listModel(this));
      this.listName.subscribe(function() {
        if (_this.listName() === '') {
          return _this.vm(new newListModel(_this));
        } else {
          return _this.vm(new listModel(_this));
        }
      });
      this.resetData = function() {
        return reset_data();
      };
      this.showJSON = function() {
        if (_this.vm().items) {
          _this.json(ko.mapping.toJSON(_this.vm().items));
        }
        _this.showingJSON(true);
        return setTimeout(function() {
          return _this.showingJSON(false);
        }, 10000);
      };
      this.newList = function() {
        Session.set('listName', '');
        return true;
      };
      this.delArchived = function() {
        return Items.remove({
          list: this.listName(),
          archived: true
        });
      };
      this.archiveAll = function() {
        var itm, _i, _len, _ref;
        if (_this.vm().items) {
          _ref = _this.vm().items();
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            itm = _ref[_i];
            Items.update(itm._id(), {
              $set: {
                archived: true
              }
            });
          }
        }
      };
    };
    canonicalListName = function(name) {
      return name.replace(/[^A-z0-9\s]*/g, '').replace(/\s+/g, '-');
    };
    Session.set('listName', window.location.hash.replace('#!', '') || '');
    vm = new viewModel();
    Meteor.startup(function() {
      return ko.applyBindings(vm);
    });
  }

  if (Meteor.is_server) {
    Meteor.startup(function() {
      if (Items.find().count() === 0) {
        return reset_data();
      }
    });
  }

}).call(this);
