// Generated by CoffeeScript 1.3.3
(function() {
  var Items, cancelEvent, changeIndent, indent, outdent, reset_data, setIndentClass;

  Items = new Meteor.Collection('items');

  reset_data = function() {
    var curItem;
    Items.remove({});
    curItem = Items.insert({
      item: 'First Item',
      indent: 0,
      isEditing: false
    });
    curItem = Items.insert({
      item: 'Second Item',
      indent: 0,
      isEditing: false
    });
  };

  if (Meteor.is_client) {
    cancelEvent = function(e) {
      if ((e != null) && (e.stopPropogation != null)) {
        e.stopPropogation;
      }
      if ((window.event != null) && (window.event.cancelBubble != null)) {
        window.event.cancelBubble = true;
      }
      if ((e != null) && (e.preventDefault != null)) {
        return e.preventDefault;
      }
    };
    setIndentClass = function(el, indent) {
      el.removeClass();
      return el.addClass('indent' + indent);
    };
    changeIndent = function(evt, el, fn, fnKey) {
      if (evt.type === 'keydown' && (typeof fnKey === "function" ? fnKey() : void 0)) {
        return;
      } else {
        cancelEvent(evt);
      }
      if (typeof fn === "function") {
        fn();
      }
      if (el != null) {
        if (typeof el.focus === "function") {
          el.focus();
        }
      }
      return false;
    };
    outdent = function(evt, el, fn) {
      return changeIndent(evt, el, fn, function() {
        return !(evt.which === 9 && evt.shiftKey);
      });
    };
    indent = function(evt, el, fn) {
      return changeIndent(evt, el, fn, function() {
        return evt.which !== 9;
      });
    };
    _.extend(Template.socialist, {
      items: function() {
        return Items.find({});
      }
    });
    _.extend(Template.navbar, {
      events: {
        'click .reset_data': function() {
          return reset_data();
        }
      }
    });
    _.extend(Template.item, {
      events: {
        'click .remove': function() {
          return Items.remove(this._id);
        },
        'click .itemView': function() {
          return Items.update(this._id, {
            isEditing: true,
            item: this.item,
            indent: this.indent
          });
        },
        'click .outdent, keydown .itemEditingInput': function(evt) {
          var _this = this;
          return outdent(evt, $('.item_' + this._id), function() {
            return Items.update(_this._id, {
              $inc: {
                indent: -1
              }
            });
          });
        },
        'click .indent, keydown .itemEditingInput': function(evt) {
          var _this = this;
          return indent(evt, $('.item_' + this._id), function() {
            return Items.update(_this._id, {
              $inc: {
                indent: 1
              }
            });
          });
        },
        'click .done, keyup .itemEditingInput': function(evt) {
          if (evt.type === 'keyup' && evt.which !== 13) {
            return;
          }
          return Items.update(this._id, {
            isEditing: false,
            item: $('.item_' + this._id).val(),
            indent: this.indent
          });
        }
      }
    });
    _.extend(Template.itemNew, {
      newItem: {
        item: '',
        indent: 0
      },
      events: {
        'click .outdent, keydown .itemEditingInput': function(evt) {
          var _this = this;
          return outdent(evt, $('.item_new'), function() {
            _this.indent--;
            return setIndentClass($('.item_new').parent(), _this.indent);
          });
        },
        'click .indent, keydown .itemEditingInput': function(evt) {
          var _this = this;
          return indent(evt, $('.item_new'), function() {
            _this.indent++;
            return setIndentClass($('.item_new').parent(), _this.indent);
          });
        },
        'click .done, keyup .itemEditingInput': function(evt) {
          if (evt.type === 'keyup' && evt.which !== 13) {
            return;
          }
          Items.insert({
            isEditing: false,
            item: $('.item_new').val(),
            indent: this.indent
          });
          return $('.item_new').val('');
        }
      }
    });
  }

  if (Meteor.is_server) {
    Meteor.startup(function() {
      if (Items.find().count() === 0) {
        return reset_data();
      }
    });
  }

}).call(this);
